feat(auto-revert): implement auto-skip and squash in auto-revert

diff --git a/git-auto-revert b/git-auto-revert
--- a/git-auto-revert
+++ b/git-auto-revert
@@ -44,6 +44,8 @@ print_usage() {
     -m, --message         commit message for single revert commit. ignored if not reverting in a single commit
     -n, --no-commit       don't automatically commit
     -e, --[no-]edit       edit the commit message
+    --[no-]auto-skip-empty
+                          automatically skip commits which have no change to be reverted
     --grep=<pattern>      limit the commits to be reverted to ones with a log message that match the specified pattern. required if <tag> is not specified
     --author=<pattern>    author to filter commits to revert. set to \"me\" to revert only the commits authored by the current user
     --committer=<pattern> committer to filter commits to revert. set to \"me\" to revert only the commits comitted by the current user
@@ -101,6 +103,7 @@ validate_options() {
 
 parse_options() {
   grep=()
+  auto_skip_empty=true
 
   if [[ ! "$1" == -* ]]; then
     OPTIND=2
@@ -109,8 +112,8 @@ parse_options() {
     OPTIND=1
   fi
 
-  local long_opts="help,single-commit,message:,no-commit,edit,no-edit,grep:,author:,committer:,since:,after:,until:,before:,since-commit:"
-  long_opts+=",after-commit:,until-commit:,before-commit:,since-tag:,after-tag:,until-tag:,before-tag:"
+  local long_opts="help,single-commit,message:,no-commit,edit,no-edit,auto-skip-empty,no-auto-skip-empty,grep:,author:,committer:"
+  long_opts+=",since:,after:,until:,before:,since-commit:,after-commit:,until-commit:,before-commit:,since-tag:,after-tag:,until-tag:,before-tag:"
   long_opts+=",conventional,all-match,invert-grep,regexp-ignore-case,basic-regexp,extended-regexp,fixed-strings,perl-regexp"
 
   while get_options "hsm:neiEFP" "$long_opts" opt "$@"; do
@@ -130,6 +133,12 @@ parse_options() {
       ;;
     e | edit)
       edit=true
+      ;;
+    auto-skip-empty)
+      auto_skip_empty=true
+      ;;
+    no-auto-skip-empty)
+      auto_skip_empty=false
       ;;
     no-edit)
       edit=false
@@ -295,10 +304,31 @@ build_commit_message() {
   commit_message+=$'\n\n'
 
   for commit in "${commit_hashes[@]}"; do
+    if is_skipped "$commit"; then
+      continue
+    fi
     commit_message+="This reverts commit $commit."$'\n'
   done
 
   printf "$commit_message"
+}
+
+is_skippable() {
+  local gitdir="$(get_git_dir)"
+  has_sequencer && ! [ -f "$gitdir/REVERT_HEAD" ] && ! has_staged_changes && ! has_unstaged_changes
+}
+
+is_skipped() {
+  local commit="$1"
+
+  for skipped_commit in "${skipped_commit_hashes[@]}"; do
+    if [ "$skipped_commit" == "$commit" ]; then
+      true
+      return
+    fi
+  done
+
+  false
 }
 
 commit() {
@@ -314,33 +344,70 @@ commit() {
   git commit -m "$message" ${commit_opts[@]}
 }
 
+squash_commits() {
+  local base_commit="$1"
+  git reset $base_commit --soft
+  commit
+}
+
 revert() {
   if [ -z "$commit_hashes" ]; then
     error "no matching commits found. nothing to do" $RET_GENERIC_ERROR
   fi
 
+  local base_commit=$(resolve_revision HEAD)
+
   local revert_opts=()
 
-  if [ "$no_commit" == "true" ] || [ "$single_commit" == "true" ]; then
+  if [ "$no_commit" == "true" ]; then
     revert_opts+=(--no-commit)
   fi
 
-  if [ "$edit" == "true" ]; then
+  if [ "$edit" == "true" ] && [ "$single_commit" != "true" ]; then
     revert_opts+=(--edit)
   else
     revert_opts+=(--no-edit)
   fi
 
-  git revert ${revert_opts[@]} ${commit_hashes[@]}
+  git revert ${revert_opts[@]} ${commit_hashes[@]} >/dev/null
 
   local revert_result=$?
+  skipped_commit_hashes=()
 
-  if [ $revert_result -eq 0 ]; then
+  if [ $revert_result -ne 0 ] && [ "$auto_skip_empty" == "true" ]; then
+    while [ $revert_result -ne 0 ] && is_skippable; do
+      local next_todo=$(get_next_todo)
+
+      git revert --skip >/dev/null
+      revert_result=$?
+
+      local todo_parts
+      IFS=' ' read -r -a todo_parts <<<"$next_todo"
+      skipped_commit_hashes+=($(resolve_revision ${todo_parts[1]}))
+    done
+  fi
+
+  local numreverted=$((${#commit_hashes[@]} - ${#skipped_commit_hashes[@]}))
+
+  if [ $numreverted -eq 0 ]; then
+    echo "All matched commits are skipped. Nothing to revert"
+  elif [ $revert_result -eq 0 ]; then
     if [ "$single_commit" == "true" ]; then
-      commit
+      squash_commits "$base_commit"
     fi
 
-    echo "Successfully reverted ${#commit_hashes[@]} commits"
+    printf "Successfully reverted $numreverted commit(s)"
+    if [ ${#skipped_commit_hashes[@]} -ne 0 ]; then
+      printf " (skipped ${#skipped_commit_hashes[@]})"
+    fi
+    echo ""
+  else
+    error "unable to revert" 0
+    if has_sequencer && (has_staged_changes || has_unstaged_changes); then
+      hint "fix the conflicts and use \"git revert --continue\" to continue the revert operation manually"
+      hint "or use \"git revert --abort\" to cancel the revert operation"
+    fi
+    fatal "auto-revert failed" $RET_GENERIC_ERROR
   fi
 }
 
